
AZURE_CLIENT_SECRET:REDACTED_SECRET
sonar qube token - REDACTED_SECRET
"CLIENT_SECRET":REDACTED_SECRET,
"grafana_api_token": "REDACTED_SECRET
IAM user access key - REDACTED_SECRET
IAM user secret key -  ZEqCS4GqM3rp5TZZOhWYiFM7GSVXgXXsEO6EzseE
"X-Jira-Token": "REDACTED_SECRET",
OpenAI - REDACTED_SECRET 



REDACTED_SECRET
REDACTED_SECRET
REDACTED_SECRET
REDACTED_SECRET
ghp_bfkqDCjWDprrrFTWCDASr0ETVrLwXj5OPBQy
ghp_bfkqDCjWDprrrFTWCDASr0ETVrLwXj6OPBQy
ghp_bfkqDCjWDprrrFTWCDASr0ETVrLwXj7OPBQy
ghp_bfkqDCjWDprrrFTWCDASr0ETVrLwXj8OPBQy
